name: tld
channels:
  - huggingface
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - charset-normalizer=3.2.0
  - click=8.0.4
  - comm=0.1.2
  - contourpy=1.0.5
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.4.9
  - ffmpeg=4.3
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.2.0
  - intel-openmp=2023.1.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - jedi=0.18.1
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=10.0.1
  - libedit=3.1.20191231
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgomp=13.1.0
  - libhwloc=2.8.0
  - libiconv=1.16
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libstdcxx-ng=13.1.0
  - libtasn1=4.19.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - lz4-c=1.9.4
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - numpy=1.25.1
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.1.1
  - packaging=23.1
  - pandas=1.5.3
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=23.2.1
  - platformdirs=2.5.2
  - pooch=1.4.0
  - prompt-toolkit=3.0.36
  - protobuf=3.20.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pymongo=3.12.0
  - pyparsing=3.0.9
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pysocks=1.7.1
  - python=3.9.17
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - readline=8.2
  - regex=2022.7.9
  - requests=2.31.0
  - sacremoses=master
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - setuptools=68.0.0
  - sip=6.5.1
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=2.0.4
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.21.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - async-timeout==4.0.2
      - attrs==23.1.0
      - datasets==2.14.2
      - dill==0.3.7
      - evaluate==0.4.0
      - filelock==3.12.2
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - huggingface-hub==0.16.4
      - multidict==6.0.4
      - multiprocess==0.70.15
      - psutil==5.9.5
      - pyarrow==12.0.1
      - pyyaml==6.0.1
      - responses==0.18.0
      - safetensors==0.3.1
      - tokenizers==0.13.3
      - transformers==4.30.0
      - xxhash==3.3.0
      - yarl==1.9.2
